library("arules")
movies<-read.csv("C:\\Data_science\\EXCLER\\My Assignments\\my_movies.csv")
str(movies)
movies$Sixth.Sense = as.factor(movies$Sixth.Sense)
movies$Gladiator = as.factor(movies$Gladiator)
movies$LOTR = as.factor(movies$LOTR)
movies$LOTR1 = as.factor(movies$LOTR1)
movies$LOTR2 = as.factor(movies$LOTR2)
movies$Harry.Potter1 = as.factor(movies$Harry.Potter1)
movies$Harry.Potter2 = as.factor(movies$Harry.Potter2)
movies$Patriot = as.factor(movies$Patriot)
movies$Braveheart = as.factor(movies$Braveheart)
movies$Green.Mile = as.factor(movies$Green.Mile)
str(movies)
rules<-apriori(movies)
arules::inspect(rules)
rules2<-apriori(movies , parameter = list(minlen=1, maxlen=15, supp=0.2,conf=0.6),
                appearance = list(lhs="V1=Sixth Sense"))
arules::inspect(head(rules2, n =5,by = 'lift'))
